### PR TITLE
 a huge amount of updates to gradles, dependencies, and related code

### PR DESCRIPTION
**Pull request by TacoTheDank**
aight babe its been a year since any actual changes so its about time it was updated

### CODE REVIEW

**Comment by harjot-oberai** [comment]
Thanks for updating the dependencies and other stuff, I had been delaying this for far too long. It will take me some time to review everything.

**Comment by TacoTheDank** [comment]
gonna be making some more changes to accommodate the results of apk testing, namely trying to fix something causing crashes when certain buttons are pressed (i actually suck at coding tbh)

ill just implement crashlytics back for the sake of it

**Comment by harjot-oberai** [comment]
Yup, I noticed that you removed crashlytics. It ok though, no need to add it back. I was already thinking of moving on to something like **sentry**.

**Comment by harjot-oberai** [comment]
Sorry, I closed this accidentally 😅

**Comment by TacoTheDank** [comment]
lol

**Comment by TacoTheDank** [comment]
i completely redid this, but much much better https://github.com/harjot-oberai/MusicDNA/pull/66

**Pull request closed without merging**
