### PR TITLE
References #28 [Remove unused / unneeded Permission request]

### PR DESCRIPTION
**Pull request by mrdjohnson**
-Removed Microphone request -Did overall cleanup of class -Added functionality to also exit if MODIFY_AUDIO_SETTINGS is not permitted

### CODE REVIEW

**Comment by mrdjohnson** [comment]
Hmm, as far as I can tell this app does not need to make or manage phone calls either? Why is that requested?

**Comment by kdexd** [comment]
@DocJava The DNA is formed by real time sampling and FFT of song stream, hence the app needs to pause when there is an incoming call and resume when it is over.

**Comment by mrdjohnson** [comment]
Ooooh, neat! Understood. Did it need the microphone as well then?

**Comment by kdexd** [comment]
I'm not sure about that part, but logically it looks like a yes. @harjot-oberai your discretion is required.

**Comment by harjot-oberai** [comment]
Microphone is not used but the Visualizer class requires **audio record** permission for doing FFT calculations. Actually it just records a small snippet for calculations and then overwrites it.
I am yet to review this PR locally. I will probably merge it tonight if everything checks out. 👍

**Comment by harjot-oberai** [comment]
Your code had a lot of issues, see the final code that I have merged into master. Initially I had written really shoddy code and your PR seemed to fix it, but it still had issues.

**Comment by mrdjohnson** [comment]
Besides not recording audio, what was wrong with the code? Just curious.

**Pull request merged**
